# Generated by Django 4.0.2 on 2022-05-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fio',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
