# Generated by Django 4.0.2 on 2022-05-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Открыта', 'Открыта'), ('В работе', 'В работе'), ('Закрыта', 'Закрыта')], default='open', max_length=100),
        ),
    ]
