# Generated by Django 4.0.2 on 2022-05-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Открыта', 'Открыта'), ('В работе', 'В работе'), ('Закрыта', 'Закрыта')], default='Открыта', max_length=100),
        ),
    ]
