# Generated by Django 4.0.2 on 2022-05-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_alter_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(null=True, upload_to='', verbose_name='frontend/src/files/'),
        ),
    ]
