# Generated by Django 4.0.2 on 2022-06-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_alter_report_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='./frontend/src/files/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(null=True, upload_to='', verbose_name='files/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Низкий', 'Низкий'), ('Средний', 'Средний'), ('Высокий', 'Высокий')], default='low', max_length=100),
        ),
    ]
